### ISSUE TITLE
componentDidMount not called when menu bar highlighted

### ISSUE THREAD

**Issue by spunkedy** [a-ignatov-parc/tvdml#10]
From what I can see `componentDidMount` does not get triggered when the menu bar is up for non highlighted items. 

I assume this is what is happening based upon my breakpoints not being hit until I switch. 

I could be wrong though.

**Comment by a-ignatov-parc** [comment]
Interesting. I'll check it in a few hours, thanks ;)

**Comment by spunkedy** [comment]
No worries. Im not being impacted by it right now, so no rush on my side.

**Comment by a-ignatov-parc** [comment]
I've checked basic behaviour and everything seems to work fine, `componentDidMount` fires when it should be. 

I'm not sure that I correctly understand `when the menu bar is up for non highlighted items` phrase. Can you give more explanation or maybe code example if it's possible?

**Comment by a-ignatov-parc** [comment]
@spunkedy do you have any additional information about this problem or I can close this issue?

**Comment by a-ignatov-parc** [comment]
Closing this issue without having any additional information.
