### ISSUE TITLE
lifecycle methods not called in right order

### ISSUE THREAD

**Issue by f0rr0** [a-ignatov-parc/tvdml#17]
<img width="751" alt="screen shot 2017-11-30 at 1 43 01 pm" src="https://user-images.githubusercontent.com/8574219/33420413-79b1fb90-d5d4-11e7-89b9-bf23e71cbb36.png">

**Comment by a-ignatov-parc** [comment]
Thanks for posting. I'll check this problem 👍

**Comment by a-ignatov-parc** [comment]
Added test to reproduce this problem in https://github.com/a-ignatov-parc/tvdml/pull/18. Will fix it soon.

**Comment by f0rr0** [comment]
@a-ignatov-parc great thanks!

**Comment by a-ignatov-parc** [comment]
Fix published as [v5.0.0](https://github.com/a-ignatov-parc/tvdml/releases/tag/v5.0.0)
