### ISSUE TITLE
hidden write to sessionStorage

### ISSUE THREAD

**Issue by f0rr0** [a-ignatov-parc/tvdml#19]
https://github.com/a-ignatov-parc/tvdml/blob/27daa2abbf2b8dc937842a643271485a0ad4071d/src/navigation.js#L121

This is hidden inside the source. Any particular reason to write this to sessionStorage? IMO this should be left to the client

**Comment by a-ignatov-parc** [comment]
It was written [long time ago](https://github.com/a-ignatov-parc/tvdml/commit/4e8ebab3aa41aed5eb6695b0df3e3ffef0f44af4) and made as workaround to expose initial params to app developer. I agree that this wasn't the best decision :)

Now we have `broadcast` function that can pass data payload so app will be able to handle it as needed.

I'll fix this in a few days. Thanks for finding 👍

**Comment by a-ignatov-parc** [comment]
Or even faster :) 

Published fix as [v5.1.0](https://github.com/a-ignatov-parc/tvdml/releases/tag/v5.1.0).
