### ISSUE TITLE
redirect feature doesn't work

### ISSUE THREAD

**Issue by altayaydemir** [a-ignatov-parc/tvdml#28]
hello @a-ignatov-parc, thank so much for great work on this 🙏 

I've been using TVDML in my tvOS app since v2.0.4 and finally I had a chance to upgrade the dependencies but seems like ```TVDML.redirect``` method is not working as expected on the latest version. 🤔 

you can reproduce the issue by applying those changes to the boilerplate app: https://github.com/altayaydemir/tvdml-app-boilerplate/commit/5246ac92d32806ae288384711475fd460011db86

**Comment by a-ignatov-parc** [comment]
Thanks! I'll take a look at this 👍

**Comment by a-ignatov-parc** [comment]
Published in [`v6.0.4`](https://github.com/a-ignatov-parc/tvdml/releases/tag/v6.0.4)
