### ISSUE TITLE
render() is called before componentDidMount()

### ISSUE THREAD

**Issue by febbraro** [a-ignatov-parc/tvdml#30]
When debugging my components, I'm finding that `render()` is being called before `componentDidMount()` which seems counter to the component lifecycle documented here: https://reactjs.org/docs/react-component.html

Since `render()` is getting called before `componentDidMount()`  things like props and state, etc. are still null or undefined.

I have things setup like this:

index.js
```
TVDML
  .subscribe(TVDML.event.LAUNCH)
  .pipe(TVDML.render(() => (
    <document>
      <menuBarTemplate>
        <menuBar>
          <menuItem route='journal'>
            <title>Journal</title>
          </menuItem>
          <menuItem route='settings'>
            <title>Settings</title>
          </menuItem>
        </menuBar>
      </menuBarTemplate>
    </document>
  )));

TVDML
  .handleRoute('journal')
  .pipe(TVDML.render(() => (
    <RuntimeWrapper>
      <Journal/>
    </RuntimeWrapper>
  )));
```

Journal.js

```
export class Journal extends Component {
  constructor(props) {
    super(props);
    console.log("Journal.constructor");
    this.state = {
      counter: 0
    };

    // So `this` works in callbacks
    this.onButtonClick = this.onButtonClick.bind(this);
  }

  componentDidMount() {
    console.log("Journal.componentDidMount");
  }
  
  render() {
    console.log("Journal.render");
    console.log(this.state);
    console.log(this.props);

    return(
      <document>
        <alertTemplate>
          <title>Journal</title>
          <description>{this.state.counter}</description>
          <button onSelect={this.onButtonClick}><text>Click Me</text></button>
          <text>{this.state.counter}</text>
        </alertTemplate>
      </document>
    );
}

  onButtonClick() {
    console.log("Click");
    const newCounter = this.state.counter + 1;
    this.setState({ counter:  newCounter });
  }
}
```

Here is my console output:
```
[Log] Journal.constructor
[Log] Journal.render
[Log] {counter: 0}   <-- state
[Log] {}             <-- props
[Log] Journal.componentDidMount
```

This is a simplification of my component that is using redux/thunk, but this highlights that Journal.render is called before Journal.componentDidMount.  In my real component if I am trying to render a template that uses data that is setup in props, my template errors out because the data loaded via calls in `componentDidMount()` has not been loaded yet.

**Comment by a-ignatov-parc** [comment]
Hello @febbraro 

I'm afraid you understand react's documentation wrong because its clearly says:
```
componentDidMount() is invoked immediately after a component is mounted.
```
That means that it'll be called after initial render.

Also, you can see [lifecycle order](https://reactjs.org/docs/react-component.html#mounting) for initial render, update and unmount 😉

As for data loading, it's normal practice to show a spinner while your data is loading.

**Comment by febbraro** [comment]
Thanks for the quick reply. This is what happens when you are learning React AND TVMLKit at the same time, thanks for pointing out the obvious to me. I'll close this for now. :)

**Comment by a-ignatov-parc** [comment]
No problem! And good luck on your journey 😉

**Comment by a-ignatov-parc** [comment]
@febbraro I can suggest you check my [attempt to rewrite](https://github.com/a-ignatov-parc/tvos-soap4.me/tree/app-refactoring/src) my TVML app to react.js with redux. It's an unfinished prototype but maybe it'll help you somehow.
