### ISSUE TITLE
DataItem() vs. Virtual DOM

### ISSUE THREAD

**Issue by febbraro** [a-ignatov-parc/tvdml#31]
Love this library, thanks for all the work on it.  

I was wondering if you have ever done a performance test of Reacts Virtual DOM vs the TVML `DataItem()` rendering?  I'm asking because I need an infinite scroll component, and the `DataItem` approach seems very un-React.  I have about 2000 total items that would be paged 50 or so at a time. I'm about to implement infinite paginations/scrolling in a more pure React way (rerender on each page and have the Virtual DOM determine what to insert or not) and possibly via `DataItem` and compare the performance, but was wondering if you had done anything like this before.

**Comment by a-ignatov-parc** [comment]
Closing this issue. If you have any other questions feel free to reopen this issue or open another one 😉

**Comment by febbraro** [comment]
Thanks a lot for that pointer.
