### ISSUE TITLE
Navigating to a document that is not in the Menu Bar loses access to Menu Bar

### ISSUE THREAD

**Issue by febbraro** [a-ignatov-parc/tvdml#35]
Hello,

I have a section of my application called "Account" that displays user information, or a choice of a few actions if the user is not authenticated. One of those actions is "Login".  When I `TVDML.navigate('login')` to the screens for login, I lose the menu bar at the top of the screen. (Login is not IN the Menu Bar, but Account is).  Once I'm done logging in, even if I `redirect` or `navigate` to "Account" the user still does not have access to the menu bar.

I'm not sure why menu bar access disappears or how to get it back without going back through the document stack by clicking on the `menu` button. I feel like I'm missing something around the understanding of how navigation works.  Thanks for any information.

**Comment by a-ignatov-parc** [comment]
Hello @febbraro 

This is normal behavior of the navigation stack implemented in TVML. Did you try to remove `login` screen from `navigationDocument.documents` when done? The simplest way to do that is to remove the latest document with `navigationDocument.documents.pop()`.

Here is a list of all available methods in [`navigationDocument`](https://developer.apple.com/documentation/tvmljs/navigationdocument)

**Comment by febbraro** [comment]
Thanks, I have tried a few things. Some work better thank others, but I found my workaround for this through exposing login and account on the menubar conditionally based on user status.  Thanks for getting back to me.  I'll let you know when this thing goes live. :)

**Comment by a-ignatov-parc** [comment]
Great! Good luck 😉

**Comment by febbraro** [comment]
FYI in case you are interested, I wrote a Google Analytics library for TVML/ES6.  

https://www.npmjs.com/package/tvjs-google-analytics

**Comment by a-ignatov-parc** [comment]
That is really nice and could be handy to someone 👍
