### ISSUE TITLE
Testing with Jest

### ISSUE THREAD

**Issue by febbraro** [a-ignatov-parc/tvdml#36]
Do you have any guidance on how to test a TVDML application and components with Jest?

I am trying to "render" some of my components so that I can test that things like redux dispatches happen on `componentDidMount()` etc.

Currently, I have the following:

```
test('Test pulling data from API', () => {
  const catalog = TVDML.render(() => (
    <RuntimeWrapper>
      <Catalog />
    </RuntimeWrapper>
  ));
  catalog.sink();
});
```

The error I get here is:
```
ReferenceError: DOMImplementationRegistry is not defined
        at DOMImplementationRegistry (/Users/frank/Projects/crossfit-tv/web/node_modules/tvdml/dist/webpack:/src/render.js:19:10)
        at route (/Users/frank/Projects/crossfit-tv/web/node_modules/tvdml/dist/webpack:/src/render.js:103:18)
        at t (/Users/frank/Projects/crossfit-tv/web/node_modules/tvdml/dist/webpack:/src/pipelines.js:18:45)
        at process._tickCallback (internal/process/next_tick.js:68:7)
```

Any guidance on how to get some of this rendering so I can test these components?

**Comment by a-ignatov-parc** [comment]
It's definitely not going to work that way because you don't have TVML runtime. 

If we talk about testing react components and not TVML render than you are free to go with something like [enzyme](https://github.com/airbnb/enzyme) from airbnb.

**Comment by a-ignatov-parc** [comment]
Also, [react-test-renderer](https://www.npmjs.com/package/react-test-renderer) should work too. You can check some [examples in Jest docs](https://jestjs.io/docs/en/tutorial-react)

**Comment by a-ignatov-parc** [comment]
@febbraro how is it going? Need any further help?

**Comment by febbraro** [comment]
I managed to get some things going, I'm using redux/react-redux too so there were some more things to work out, but this is what it looks like.

Enzyme had some challenges because it had a dependency on react-dom which wound up being a bit of a rabbit hole, also it was looking as if we'd likely need to develop an enzyme-adapter-react-16-tvml.  I'm using react-test-renderer, for my setup it seemed to work a bit easier.

So, this works...

```
import React from 'react';
import TestRenderer from 'react-test-renderer';

import store from '../../../store/configureStore';
import RuntimeWrapper from '../../../components/RuntimeWrapper';
import Catalog from '../Catalog';

test('Test pulling catalog data from App Store', () => {
  const testRenderer = TestRenderer.create(
    <RuntimeWrapper>
      <Catalog />
    </RuntimeWrapper>,
  );

  const state = store.getState();
  expect(state.subscriptionReducer.product).toHaveProperty(['productId'], 'xxx.yyy.zzz.monthly');
});
```

Then if you need to dig deeper to get to the React components for their props and dispatch you can do something like this...

```
  // This will call some action dispatchers on the props setup via mapDispatchToProps
  const instance = testRenderer.root;
  const catalogInstance = instance.findByType(Catalog).children[0];
  catalogInstance.props.purchaseMonthly();
```

So, still chugging along, thanks for your response and pointers. I think it would be great to get Enzyme to work with React/TVML/TVDML at some point in the future as it looks like a great test framework.

**Comment by a-ignatov-parc** [comment]
Glad to hear that it's worked out 👍

I'm afraid it'll be very difficult and not worth at this time to implement enzyme adapter. TVML document model has some major differences with browsers implementation. It might be easier to create an infrastructure to run tests in the tvOS emulator directly

**Comment by febbraro** [comment]
Yeah, it looked pretty involved so I steered away from that.  I think coming up with a good plan for being able to test these TVDML apps is a good idea, once I progress in building my tests out I'll try to throw some ideas/docs in a gist that can maybe be added to the readme.

**Comment by a-ignatov-parc** [comment]
That would be awesome 👍
