### ISSUE TITLE
What happened to the TVDML.createPlayer?

### ISSUE THREAD

**Issue by spunkedy** [a-ignatov-parc/tvdml#38]
```    let url = err ? playObject.sdUri : checkedUrl;
    let urls = [ { url, title: playObject.name }];
    TVDML.createPlayer({
      items: urls,
      uidResolver(item){
        return item.url;
      }
    })
    .then(player => player.play())
    .catch(err => console.log(err));```

I am going through the upgrade to the latest, and I don't see this method anymore. 
Is this just in preference of doing it like this?

```
const player = new Player();
  const playlist = new Playlist();
  const mediaItem = new MediaItem("video", playObject.hd);
  console.log("playing");
  console.log(playObject.hd);
  
  player.playlist = playlist;
  player.playlist.push(mediaItem);
  player.play();  ```

**Comment by a-ignatov-parc** [comment]
`TVDML.createPlayer` was removed a long time ago in [v3](https://github.com/a-ignatov-parc/tvdml/releases/tag/v3.0.0).

It was too complex to support and default api is flexible enough to handle all major use cases.

**Comment by a-ignatov-parc** [comment]
Here is an official [api documentation](https://developer.apple.com/documentation/tvmljs/player).

**Comment by spunkedy** [comment]
cool, I will close this. I just wanted to make sure I didn't miss a pattern upgrade that you did.
