### ISSUE TITLE
Menubar highlight event & Component reload

### ISSUE THREAD

**Issue by john-trovalto** [a-ignatov-parc/tvdml#48]
Hey @a-ignatov-parc 

First of all a big thanks for the awesome library. It just saved our time in an ongoing project which had a limited timeline. 

Everything is working fine and smoothly but having an issue regarding data refresh. Like, we have currently 5 menu tabs and each tab shows data based on API. But we couldn't able to find the event which will tell us that the new menu tab is selected.

Each tab has its own route and API call is done in the componentDidMount function. As the component is not getting destroyed while the user navigating through menu tabs, the request will be sent only once. 

How we can reload or refresh the component when the user selects it?

Thank you.

**Comment by a-ignatov-parc** [comment]
Hi @john-trovalto 

`menu-item-select` event will help you understand when menu items selection has changed. Unfortunately, this event isn't described in the documentation. 

Combining this information with the navigation information from the initial render, you'll be able to understand when you should re-request data for the component.

Here is an example with hooks:
```jsx
import React from 'react';
import * as TVDML from 'tvdml';

TVDML.subscribe(TVDML.event.LAUNCH).pipe(
  TVDML.render(() => (
    <document>
      <menuBarTemplate>
        <menuBar>
          <menuItem route="page1">
            <title>Page1</title>
          </menuItem>
          <menuItem route="page2">
            <title>Page2</title>
          </menuItem>
        </menuBar>
      </menuBarTemplate>
    </document>
  )),
);

TVDML.handleRoute('page2').pipe(TVDML.render(props => <Page2 {...props} />));

const Page2 = ({ navigation }) => {
  React.useEffect(() => {
    const subscription = TVDML.subscribe('menu-item-select');

    subscription.pipe(({ menuItem }) => {
      if (navigation.menuItem === menuItem) {
        console.log('Menu item is focused');
      }
    });

    console.log('Initial render');

    return () => subscription.unsubscribe();
  }, [navigation.menuItem]);

  return (
    <document>
      ...
    </document>
  )
}
```

> If you're not using hooks, you should implement similar logic in the `componentDidMount`

**Comment by john-trovalto** [comment]
@a-ignatov-parc 

Awesome!  

Thank you so much for the solution. I checked and it works pretty well :)

**Comment by a-ignatov-parc** [comment]
@john-trovalto glad to hear it 🙂

I'll add information about the undocumented events to the Readme when I'll have free time 👍
