### ISSUE TITLE
When pushing menu button between routes I get a blank screen

### ISSUE THREAD

**Issue by spunkedy** [a-ignatov-parc/tvdml#9]
Flow of actions:
* Page 1 -> Page 2
* Press Menu button
* Data gets queried, render function gets called, but blank screen is there. It patches the dom but doesn't render.

If I hit the menu button again, it goes back to the previous page. 

![screen shot 2017-01-03 at 3 34 44 am](https://cloud.githubusercontent.com/assets/690735/21603850/b5be2f4c-d165-11e6-9c07-b70e47355824.png)

It seems like it could be trying to patch the DOM but for some reason isn't updating. Any ideas what might be going on?

**Comment by spunkedy** [comment]
if I pop the last document on the stack on a menu button push it seems to fix the issue.

```
componentDidMount() {
        console.log("on did mount");


        var myObj = this;
        var runWithData = function(){
          myObj.loadData().then((response) => {
            myObj.setState({
              data:response.data,
              props:props,
              passedProps:passedProps,
              loading: false
            })
          });
        }


        let currentDocument = this._rootNode.ownerDocument;
				this.menuButtonPressStream = TVDML.subscribe('menu-button-press');
				this.menuButtonPressStream
					.pipe(isMenuButtonPressNavigatedTo(currentDocument))
					.pipe(isNavigated => {
            if(isNavigated){
              console.log("clearin doc");
              navigationDocument.popDocument();
            }            
            return false;
          });
        runWithData();
      },
```

**Comment by spunkedy** [comment]
I apparently am loading multiple documents to the document stack. I will investigate. I think this is probably just a user error.

![screen shot 2017-01-03 at 4 22 02 am](https://cloud.githubusercontent.com/assets/690735/21605067/4ab8f70c-d16c-11e6-9f0f-46789e191628.png)

**Comment by a-ignatov-parc** [comment]
Interesting case. Can you show how you handling routes? I don't think that popping documents manually is a good idea but I need more information.

**Comment by spunkedy** [comment]
Sure, I will try to get a small sample repo and link it here as an example.

**Comment by a-ignatov-parc** [comment]
That would be great 👍

**Comment by spunkedy** [comment]
If you want to jump on a screen share I can show you immediately

**Comment by a-ignatov-parc** [comment]
Sorry. I'm currently not at home

**Comment by spunkedy** [comment]
No worries, I will redact what I need and get it. I might be reading the doc / mis-understanding something as well.

**Comment by a-ignatov-parc** [comment]
Thanks a lot 👍

**Comment by spunkedy** [comment]
take a look here. I can almost replicate it. 

https://github.com/spunkedy/test-tvdml

On first load there is 2 documents on the navigation document. 
On the 2nd click through it doesn't load but it also adds the document to the stack and shows 3 but an empty screen.

I think I am just missing something.

![screen shot 2017-01-03 at 2 55 25 pm](https://cloud.githubusercontent.com/assets/690735/21622785/d5fe7460-d1c4-11e6-9124-4c8ef9990359.png)

**Comment by a-ignatov-parc** [comment]
Thank you for providing code example. The problem is [here](https://github.com/spunkedy/test-tvdml/blob/master/src/lib/routin.js#L35-L38). You have overwritten pipeline's payload that contains not only params but also current document and some other data that is used during rendering.

The fix is simple:

```javascript
return TVDML
    .createPipeline()
    .pipe(TVDML.render(({navigation: {passedProps}}) => TVDML.createComponent({
        ...
    })));
```

Or even
```javascript
return TVDML
    .createPipeline()
    .pipe(TVDML.render(TVDML.createComponent({
        getInitialState() {
            console.log('state', this.props) // this.props contains pipeline data.
            
            return {
                active: null,
                loading: true,
            };
        },
        ...
    })));
```

I hope that will solve your problem ;)

**Comment by a-ignatov-parc** [comment]
I think I should add more information into `readme` about rendering.

**Comment by spunkedy** [comment]
That worked. I think I just don't fully understand the rendering side or why that fixed it. 

I am seeing some flickering once rendering. Not sure why. I will see if I can capture a vid of it.

**Comment by a-ignatov-parc** [comment]
Let me try to explain in a few words.

When you handle new route it creates empty document that is supposed to "lock" place in `navigationDocument` for upcoming renders.

`TVDML.render()` create document based on markup that was passed and push it to `navigationDocument`. New document doesn't know anything about routes or other documents. That is what happened in your case.

But if you pass payload with `document` property to `TVDML.render()` it will update that document with new markup.

I hope that will clarify at least something :)

**Comment by a-ignatov-parc** [comment]
Added additional info to `README.md` in https://github.com/a-ignatov-parc/tvdml/pull/11/commits/7ce143a06db40d8a0a09020164a8be4ffd6d2796 to clarify this behaviour.
